# -------------------------------------------
#   Configuration File for Database plugin!
# -------------------------------------------

connection:
    host: "127.0.0.1"
    port: "3306"
    user: "plugin"
    pass: "spigot"
    db: "minecraft"