name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
author: ${author}
commands:
    database:
        description: Base command
        usage: /<command> [connect|reconnect|disconnect|plugins]
        aliases: [db, connect, disconnect, reconnect]
        permission: database.command
permissions:
    database.command:
        description: Base permission
        default: op